name: TestFire DAST Scan Test CLI

# Controls when the workflow will run
on:
  pull_request:
    branches: 
      - main
  workflow_dispatch: 
  
permissions:
  contents: read

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    permissions:
      contents: read # for actions/checkout to fetch code
      security-events: write # for github/codeql-action/upload-sarif to upload SARIF results
      actions: read # only required for a private repository by github/codeql-action/upload-sarif
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v3
    # Scan
    - name: Checkmarx DAST Github Action
      uses: Checkmarx/dast-github-action@v1.0.2
      env:
        CX_APIKEY: ${{ secrets.CX_APIKEY }}
      with:
        command: "api"
        config: './testfire_api.yaml'
        base_url: "https://eu.ast.checkmarx.net"
        environment_id: "d7d10ea9-cf6d-494f-a90e-7cfbc185cf93"
        openapi: "./testfire_openapi.yaml"
        project_id: ""
        fail_on: "HIGH"
        verbose: true
        output: ./output
    - name: Reclaim output directory  
      if: always()  
      run: sudo chown -R 1001:1001 ${{ github.workspace }}/output
    - uses: actions/upload-artifact@v3
      if: always()
      name: Upload Logs
      with:
        name: report
        path: ./output
